// ============================================================================
// CENTRALIZED DUMMY DATA FOR FRONTEND
// This file contains all dummy/fallback data used across the application
// ============================================================================

// Dummy Products - Used when API data is not available
export const DUMMY_PRODUCTS = [
  {
    _id: 'dummy-1',
    name: 'Sony A7 IV Camera',
    description: 'Professional mirrorless camera with 33MP full-frame sensor',
    images: ['https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400'],
    pricing: { daily: 2500, weekly: 15000, monthly: 50000, securityDeposit: 10000 },
    ratings: { average: 4.9, count: 128 },
    category: 'Cameras',
    condition: 'Like New',
    availability: true,
    isActive: true,
    totalQuantity: 5,
    vendor: { name: 'Camera Pro Rentals', _id: 'vendor-1' },
    createdAt: new Date('2024-01-15'),
  },
  {
    _id: 'dummy-2',
    name: 'MacBook Pro 16"',
    description: 'M3 Pro chip, 18GB RAM, 512GB SSD - Perfect for professionals',
    images: ['https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400'],
    pricing: { daily: 3500, weekly: 20000, monthly: 70000, securityDeposit: 25000 },
    ratings: { average: 4.8, count: 96 },
    category: 'Electronics',
    condition: 'Excellent',
    availability: true,
    isActive: true,
    totalQuantity: 3,
    vendor: { name: 'TechHub Rentals', _id: 'vendor-2' },
    createdAt: new Date('2024-01-20'),
  },
  {
    _id: 'dummy-3',
    name: 'DJI Mavic 3 Pro',
    description: 'Professional drone with 4/3 CMOS Hasselblad camera',
    images: ['https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=400'],
    pricing: { daily: 4500, weekly: 25000, monthly: 90000, securityDeposit: 30000 },
    ratings: { average: 4.9, count: 74 },
    category: 'Electronics',
    condition: 'New',
    availability: true,
    isActive: true,
    totalQuantity: 2,
    vendor: { name: 'Drone World', _id: 'vendor-3' },
    createdAt: new Date('2024-02-01'),
  },
  {
    _id: 'dummy-4',
    name: 'Canon RF 70-200mm f/2.8L',
    description: 'Professional telephoto lens IS USM',
    images: ['https://images.unsplash.com/photo-1617005082133-548c4dd27f35?w=400'],
    pricing: { daily: 1800, weekly: 10000, monthly: 35000, securityDeposit: 15000 },
    ratings: { average: 4.7, count: 52 },
    category: 'Cameras',
    condition: 'Excellent',
    availability: false,
    isActive: false,
    totalQuantity: 1,
    vendor: { name: 'Camera Pro Rentals', _id: 'vendor-1' },
    createdAt: new Date('2024-01-10'),
  },
  {
    _id: 'dummy-5',
    name: 'JBL PartyBox 710',
    description: 'Powerful party speaker with 800W output and LED lights',
    images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?w=400'],
    pricing: { daily: 2000, weekly: 12000, monthly: 40000, securityDeposit: 8000 },
    ratings: { average: 4.6, count: 89 },
    category: 'Audio',
    condition: 'Good',
    availability: true,
    isActive: true,
    totalQuantity: 4,
    vendor: { name: 'AudioMax', _id: 'vendor-4' },
    createdAt: new Date('2024-01-25'),
  },
  {
    _id: 'dummy-6',
    name: 'Bosch Power Drill Set',
    description: 'Professional cordless drill with 50+ accessories',
    images: ['https://images.unsplash.com/photo-1504148455328-c376907d081c?w=400'],
    pricing: { daily: 500, weekly: 3000, monthly: 10000, securityDeposit: 2000 },
    ratings: { average: 4.5, count: 145 },
    category: 'Tools',
    condition: 'Good',
    availability: true,
    isActive: true,
    totalQuantity: 10,
    vendor: { name: 'ToolMaster', _id: 'vendor-5' },
    createdAt: new Date('2024-02-05'),
  },
  {
    _id: 'dummy-7',
    name: 'GoPro Hero 12 Black',
    description: 'Action camera with 5.3K60 video and waterproof housing',
    images: ['https://images.unsplash.com/photo-1606986628110-e66a8b4cb21e?w=400'],
    pricing: { daily: 1200, weekly: 7000, monthly: 25000, securityDeposit: 5000 },
    ratings: { average: 4.8, count: 112 },
    category: 'Cameras',
    condition: 'Like New',
    availability: true,
    isActive: true,
    totalQuantity: 6,
    vendor: { name: 'Camera Pro Rentals', _id: 'vendor-1' },
    createdAt: new Date('2024-02-10'),
  },
  {
    _id: 'dummy-8',
    name: 'Godox AD600 Pro',
    description: 'Professional studio flash with 600Ws power',
    images: ['https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?w=400'],
    pricing: { daily: 2200, weekly: 13000, monthly: 45000, securityDeposit: 12000 },
    ratings: { average: 4.7, count: 68 },
    category: 'Cameras',
    condition: 'Excellent',
    availability: true,
    isActive: true,
    totalQuantity: 3,
    vendor: { name: 'Camera Pro Rentals', _id: 'vendor-1' },
    createdAt: new Date('2024-01-18'),
  },
];

// Dummy Categories
export const DUMMY_CATEGORIES = [
  { id: 'Electronics', name: 'Electronics', icon: 'electronics', count: 2 },
  { id: 'Cameras', name: 'Cameras', icon: 'cameras', count: 5 },
  { id: 'Tools', name: 'Tools', icon: 'tools', count: 1 },
  { id: 'Audio', name: 'Audio', icon: 'audio', count: 1 },
  { id: 'Furniture', name: 'Furniture', icon: 'furniture', count: 0 },
  { id: 'Outdoor', name: 'Outdoor', icon: 'sports', count: 0 },
  { id: 'Transport', name: 'Transport', icon: 'default', count: 0 },
  { id: 'Other', name: 'Other', icon: 'default', count: 0 },
];

// Condition options
export const CONDITIONS = ['All Conditions', 'New', 'Like New', 'Excellent', 'Good', 'Fair'];

// Sort options
export const SORT_OPTIONS = [
  { value: 'relevance', label: 'Relevance' },
  { value: 'price-low', label: 'Price: Low to High' },
  { value: 'price-high', label: 'Price: High to Low' },
  { value: 'rating', label: 'Highest Rated' },
  { value: 'newest', label: 'Newest First' },
];
